import type {
  Asset,
  Fund,
  InvestorProfile,
  MarketEvent,
  OpportunityAnalysis,
  OpportunityDailyReport,
  OpportunityFeedback,
  OpportunitySignal,
  OpportunitySource,
  RawExternalItem,
  ReviewRecord,
  Stock,
  TradeDecision,
  WatchItem,
} from "./types";

const now = "2026-07-01";

export const defaultInvestorProfile: InvestorProfile = {
  totalAssets: 1400000,
  availableCash: 360000,
  riskTolerance: "balanced",
  maxEquityRatio: 40,
  targetEquityRatio: 25,
  maxSingleStockRatio: 10,
  maxSingleFundRatio: 20,
  maxSingleTradeRatio: 3,
  preferredMarkets: ["A_SHARE", "HK", "US"],
  preferredSectors: ["品牌消费", "文旅商业", "科技趋势", "新消费", "AI 应用", "城市更新", "医疗健康", "稳健基金配置"],
  forbiddenSectors: [],
  investmentGoal: "在控制风险的前提下，逐步提升长期资产收益率。",
  updatedAt: now,
};

export const mockAssets: Asset[] = [
  {id: "asset-1", name: "银行定期", type: "fixed_deposit", amount: 1000000, annualYield: 2.2, createdAt: now, updatedAt: now},
  {id: "asset-2", name: "余额宝", type: "money_fund", amount: 260000, annualYield: 1.5, createdAt: now, updatedAt: now},
  {id: "asset-3", name: "基金账户", type: "fund", amount: 40000, createdAt: now, updatedAt: now},
  {id: "asset-4", name: "证券账户现金", type: "stock", amount: 100000, createdAt: now, updatedAt: now},
];

export const mockFunds: Fund[] = [
  {
    id: "fund-1",
    name: "稳健成长混合",
    code: "000001",
    type: "hybrid",
    holdingAmount: 26000,
    cost: 1.12,
    currentNav: 1.18,
    returnRate: 5.4,
    holdingDays: 188,
    targetProfitRate: 18,
    maxAcceptableLossRate: 15,
    monthlyInvestment: 2000,
    manager: "陈明",
    fundSize: 86,
    oneYearReturn: 8.6,
    threeYearReturn: 26.4,
    maxDrawdown: 12,
    volatility: 13,
    industries: ["消费", "医药", "高端制造"],
    investmentReason: "作为权益仓位的核心观察项，风格相对均衡，适合长期分批配置。",
    holdReason: "回撤控制较好，和现金资产形成收益弹性互补。",
    exitCondition: "基金经理变更、长期跑输同类或收益达到目标后重新评估。",
    note: "作为权益仓位的核心观察项，回撤控制较好。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "fund-2",
    name: "沪深300指数增强",
    code: "000300",
    type: "index",
    holdingAmount: 14000,
    cost: 1.03,
    currentNav: 0.98,
    returnRate: -4.8,
    holdingDays: 96,
    targetProfitRate: 15,
    maxAcceptableLossRate: 18,
    monthlyInvestment: 1500,
    manager: "李晨",
    fundSize: 124,
    oneYearReturn: 4.2,
    threeYearReturn: 15.5,
    maxDrawdown: 21,
    volatility: 18,
    industries: ["金融", "消费", "科技"],
    investmentReason: "宽基指数增强，用于建立基础权益仓位。",
    holdReason: "估值不高时适合分批配置，避免单一行业暴露。",
    exitCondition: "指数估值明显偏高或增强长期失效时减仓。",
    note: "宽基配置，适合分批而不是一次性买入。",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockStocks: Stock[] = [
  {
    id: "stock-1",
    name: "贵州茅台",
    code: "600519",
    market: "A_SHARE",
    status: "watching",
    industry: "消费",
    currentPrice: 1460,
    targetBuyPrice: 1300,
    targetSellPrice: 1800,
    stopLossPrice: 1180,
    shares: 0,
    cost: 0,
    pe: 24,
    pb: 8.6,
    revenueGrowth: 15,
    profitGrowth: 16,
    grossMargin: 91,
    netMargin: 52,
    roe: 31,
    cashFlow: 680,
    debtRatio: 18,
    industryTrend: "neutral",
    investmentReason: "高质量消费龙头，但需要等待足够安全边际。",
    riskReason: "估值不便宜，消费复苏节奏需要观察。",
    exitCondition: "基本面下滑或估值显著透支时放弃观察。",
    note: "高质量但估值不便宜，适合等待更好的安全边际。",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "stock-2",
    name: "腾讯控股",
    code: "00700",
    market: "HK",
    status: "holding",
    industry: "互联网",
    holdingAmount: 38200,
    currentPrice: 382,
    targetBuyPrice: 340,
    targetSellPrice: 480,
    stopLossPrice: 320,
    shares: 100,
    cost: 405,
    pe: 18,
    pb: 3.8,
    revenueGrowth: 8,
    profitGrowth: 21,
    grossMargin: 51,
    netMargin: 23,
    roe: 18,
    cashFlow: 2100,
    debtRatio: 32,
    industryTrend: "neutral",
    investmentReason: "现金流和盈利质量较稳，作为港股科技龙头小仓位观察。",
    riskReason: "监管、游戏和广告增长节奏仍需跟踪。",
    exitCondition: "利润增长转弱或触发止损线时复盘。",
    note: "现金流和盈利质量较稳，需关注监管与业务增长节奏。",
    createdAt: now,
    updatedAt: now,
  },
];

export const storagePriceEvent: MarketEvent = {
  id: "event-storage-2026",
  title: "移动硬盘与存储芯片涨价",
  eventDate: "2026-07-01",
  eventType: "price_increase",
  summary: "AI 数据中心需求增长，可能带动企业级 SSD、DRAM、NAND、HDD 等存储产品需求上升。如果供给端扩产跟不上，相关产业链公司可能受益。",
  affectedSectors: ["存储芯片", "半导体", "AI 服务器", "数据中心", "算力基础设施"],
  industryChain: {
    upstream: ["DRAM", "NAND Flash", "HBM", "硬盘核心部件"],
    midstream: ["SSD", "HDD", "企业级存储", "服务器存储设备"],
    downstream: ["AI 数据中心", "云计算厂商", "服务器厂商", "消费电子"],
  },
  relatedStocks: [
    {name: "Micron Technology", code: "MU", market: "US", sector: "存储芯片", reason: "DRAM、NAND 和 HBM 相关业务可能受益于 AI 存储需求。", risk: "周期股属性明显，价格上涨可能已部分反映在股价中。", action: "observe"},
    {name: "Western Digital", code: "WDC", market: "US", sector: "硬盘与存储", reason: "企业级存储需求提升可能带动 HDD 与数据中心存储业务。", risk: "行业周期强，股价波动较大。", action: "wait_for_pullback"},
    {name: "Seagate", code: "STX", market: "US", sector: "硬盘与存储", reason: "HDD 需求受 AI 数据中心和云存储扩容影响。", risk: "若存储价格回落，盈利预期可能下修。", action: "observe"},
  ],
  relatedFunds: [
    {name: "半导体 ETF", fundType: "ETF", reason: "可以通过 ETF 分散参与半导体产业链机会。", risk: "半导体 ETF 可能已经包含大量高估值标的。", action: "small_position"},
    {name: "纳斯达克 100 ETF", fundType: "ETF", reason: "间接覆盖美股 AI、云计算和科技龙头。", risk: "美股科技股估值波动较大。", action: "observe"},
  ],
  confidenceLevel: 4,
  riskLevel: "high",
  conclusion: "该事件属于高景气、高波动机会，适合加入观察池，不适合直接重仓追涨。更合理的方式是等待回调，或通过 ETF 小额分批参与。",
  createdAt: now,
};

export const mockWatchItems: WatchItem[] = [
  {
    id: "watch-1",
    instrumentType: "event",
    name: "移动硬盘与存储芯片涨价",
    source: "market_radar",
    watchReason: "AI 数据中心需求可能带来存储产业链景气度提升，但追高风险较高。",
    triggerCondition: "相关 ETF 回调或龙头估值回到可接受区间。",
    riskNote: "周期性强，事件可能已经被市场提前定价。",
    status: "watching",
    createdAt: now,
    updatedAt: now,
  },
];

export const mockOpportunitySources: OpportunitySource[] = [
  {
    id: "source-1",
    sourceName: "GDELT Global News",
    sourceType: "gdelt",
    sourceUrl: "https://api.gdeltproject.org/api/v2/doc/doc",
    apiProvider: "gdelt",
    keywords: ["AI", "semiconductor", "storage", "data center", "robot", "battery", "gold", "oil", "copper", "interest rate", "China economy", "US inflation", "electric vehicle", "pharmaceutical", "tourism", "consumer spending"],
    enabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {id: "source-2", sourceName: "Reuters Business RSS", sourceType: "rss", sourceUrl: "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best", apiProvider: "rss", enabled: true, createdAt: now, updatedAt: now},
  {id: "source-3", sourceName: "MIT Technology Review", sourceType: "rss", sourceUrl: "https://www.technologyreview.com/feed/", apiProvider: "rss", enabled: true, createdAt: now, updatedAt: now},
  {id: "source-4", sourceName: "SEC EDGAR Company Filings", sourceType: "sec", sourceUrl: "https://data.sec.gov/submissions/", apiProvider: "sec", tickers: ["AAPL", "MSFT", "NVDA", "TSLA"], enabled: false, createdAt: now, updatedAt: now},
  {id: "source-5", sourceName: "FRED Macro Indicators", sourceType: "fred", sourceUrl: "https://api.stlouisfed.org/fred/series/observations", apiProvider: "fred", indicators: ["FEDFUNDS", "CPIAUCSL", "UNRATE", "DGS10", "DGS2", "M2SL", "DTWEXBGS"], enabled: true, createdAt: now, updatedAt: now},
];

export const mockRawExternalItems: RawExternalItem[] = [
  {
    id: "raw-storage-price",
    sourceId: "source-1",
    title: "AI data center storage demand lifts memory and disk attention",
    summary: "AI 数据中心需求提升，企业级 SSD、HDD 和高性能存储组件被密集讨论。",
    url: "https://example.com/storage-demand",
    publishedAt: now,
    rawContent: "AI data center storage demand lifts memory and disk attention. Enterprise SSD, HDD and HBM supply chain coverage increased.",
    detectedKeywords: ["AI", "data center", "storage", "HBM"],
    hash: "raw-storage-price",
    createdAt: now,
  },
  {
    id: "raw-robot-demand",
    sourceId: "source-3",
    title: "Robotics commercialization moves from prototype to early production",
    summary: "机器人商业化节点被密集报道，传感器、减速器、伺服系统和轻量化材料关注度上升。",
    url: "https://example.com/robot-production",
    publishedAt: now,
    rawContent: "Robotics commercialization moves from prototype to early production with actuator, sensor and reducer suppliers in focus.",
    detectedKeywords: ["robot", "sensor", "automation"],
    hash: "raw-robot-demand",
    createdAt: now,
  },
];

export const mockOpportunitySignals: OpportunitySignal[] = [
  {
    id: "signal-storage-price",
    sourceId: "source-1",
    rawItemId: "raw-storage-price",
    signalTitle: "存储设备价格上涨引发产业链机会预警",
    signalType: "price_anomaly",
    rawContent: "AI 数据中心需求提升，企业级 SSD、HDD 和高性能存储组件被密集讨论，部分渠道价格出现上行。",
    keywords: ["存储设备", "SSD", "HDD", "AI 数据中心", "HBM"],
    relatedIndustries: ["存储芯片", "硬盘制造", "服务器", "云计算基础设施"],
    relatedCompanies: ["Micron Technology", "Western Digital", "Seagate"],
    signalStrength: 86,
    confidenceScore: 78,
    detectedAt: now,
    createdAt: now,
  },
  {
    id: "signal-robot-demand",
    sourceId: "source-3",
    rawItemId: "raw-robot-demand",
    signalTitle: "人形机器人量产预期升温",
    signalType: "demand_boom",
    rawContent: "多家公司公布机器人商业化进展，传感器、减速器、伺服系统和轻量化材料关注度上升。",
    keywords: ["机器人", "减速器", "伺服系统", "传感器"],
    relatedIndustries: ["机器人零部件", "工业自动化", "传感器", "高端制造"],
    relatedCompanies: ["汇川技术", "绿的谐波", "Tesla"],
    signalStrength: 78,
    confidenceScore: 70,
    detectedAt: now,
    createdAt: now,
  },
  {
    id: "signal-low-altitude-policy",
    sourceId: "source-2",
    signalTitle: "低空经济政策密集发布",
    signalType: "policy_catalyst",
    rawContent: "多个地区继续发布低空经济支持政策，基础设施、空管系统、无人机运营和应用场景进入验证期。",
    keywords: ["低空经济", "无人机", "空管系统", "基础设施"],
    relatedIndustries: ["无人机", "空管系统", "通航运营", "低空基础设施"],
    relatedCompanies: ["中无人机", "航天电子", "亿航智能"],
    signalStrength: 73,
    confidenceScore: 66,
    detectedAt: now,
    createdAt: now,
  },
  {
    id: "signal-consumer-contrarian",
    sourceId: "source-2",
    signalTitle: "消费龙头估值压缩后的反向观察",
    signalType: "contrarian",
    rawContent: "消费板块整体情绪偏弱，但部分现金流稳定公司基本面未明显恶化，估值进入历史较低区间。",
    keywords: ["消费", "估值压缩", "现金流", "反向机会"],
    relatedIndustries: ["食品饮料", "品牌消费", "零售"],
    relatedCompanies: ["贵州茅台", "腾讯控股"],
    signalStrength: 64,
    confidenceScore: 62,
    detectedAt: now,
    createdAt: now,
  },
];

export const mockOpportunityAnalyses: OpportunityAnalysis[] = [
  {
    id: "analysis-storage-price",
    signalId: "signal-storage-price",
    title: "存储设备价格上涨引发产业链机会预警",
    signalSources: ["GDELT Global Events", "渠道价格摘要", "科技新闻源"],
    whatHappened: "近期存储设备价格出现上涨，AI 数据中心扩容带来的企业级存储需求被多类新闻源反复提及。",
    whyItMatters: "如果价格上涨来自真实需求增长或供给紧张，可能影响存储芯片、硬盘、服务器和数据中心资本开支。",
    transmissionChain: ["存储设备涨价", "存储芯片需求和价格变化", "硬件厂商订单改善", "云计算和数据中心资本开支变化", "相关公司业绩预期变化"],
    beneficiaryIndustries: ["存储芯片", "硬盘制造", "服务器", "云计算基础设施", "数据中心"],
    beneficiaryCompanyTypes: ["具有企业级存储订单的制造商", "HBM/DRAM/NAND 供应商", "数据中心服务器供应链公司"],
    relatedTickers: [
      {name: "Micron Technology", code: "MU", market: "US", reason: "DRAM、NAND 和 HBM 相关业务可能受益于 AI 存储需求。"},
      {name: "Western Digital", code: "WDC", market: "US", reason: "企业级 HDD 与数据中心存储业务对价格周期敏感。"},
      {name: "Seagate", code: "STX", market: "US", reason: "云存储扩容可能改善 HDD 需求预期。"},
    ],
    riskPoints: ["价格上涨可能只是短期渠道波动。", "相关股票可能已经提前反映预期。", "存储行业周期性强，盈利兑现需要跟踪库存和合同价格。"],
    nextQuestions: ["涨价是否持续超过一个季度？", "公司财报中毛利率和库存是否同步改善？", "数据中心资本开支是否继续上修？"],
    scoreBreakdown: {signalStrength: 18, chainClarity: 18, fundamentalRelevance: 17, valuationSafety: 13, userFit: 15},
    opportunityScore: 81,
    suitabilityScore: 75,
    riskLevel: "high",
    status: "new",
    conclusion: "加入观察池，不直接买入。下一步应研究相关公司财报、库存、订单、毛利率和估值位置。",
    createdAt: now,
  },
  {
    id: "analysis-robot-demand",
    signalId: "signal-robot-demand",
    title: "人形机器人量产预期升温",
    signalSources: ["MIT Technology Review", "行业媒体 RSS", "公司发布会摘要"],
    whatHappened: "机器人商业化节点被密集报道，市场开始关注从样机展示到小批量量产的产业链变化。",
    whyItMatters: "如果需求从概念验证走向订单，传感器、减速器、伺服系统和控制软件可能出现真实收入弹性。",
    transmissionChain: ["产品化进展", "核心零部件需求增加", "供应链订单验证", "利润率和产能利用率变化", "相关公司估值重新定价"],
    beneficiaryIndustries: ["机器人零部件", "工业自动化", "传感器", "高端制造"],
    beneficiaryCompanyTypes: ["核心零部件供应商", "具备批量交付能力的自动化公司", "客户验证进展清晰的软件与控制系统公司"],
    relatedTickers: [
      {name: "汇川技术", code: "300124", market: "A_SHARE", reason: "工业自动化和控制系统能力较强，可作为产业链研究样本。"},
      {name: "绿的谐波", code: "688017", market: "A_SHARE", reason: "谐波减速器属于机器人核心零部件。"},
      {name: "Tesla", code: "TSLA", market: "US", reason: "机器人商业化叙事的重要观察对象。"},
    ],
    riskPoints: ["量产节奏可能低于预期。", "估值可能先于订单大幅反应。", "部分公司可能只是概念相关，收入占比很低。"],
    nextQuestions: ["是否有真实订单和交付节奏？", "核心零部件毛利率是否改善？", "公司机器人业务收入占比是多少？"],
    scoreBreakdown: {signalStrength: 15, chainClarity: 16, fundamentalRelevance: 15, valuationSafety: 11, userFit: 14},
    opportunityScore: 71,
    suitabilityScore: 68,
    riskLevel: "high",
    status: "new",
    conclusion: "加入观察池，先验证订单和收入占比，不把产品发布会等同于投资价值。",
    createdAt: now,
  },
  {
    id: "analysis-low-altitude-policy",
    signalId: "signal-low-altitude-policy",
    title: "低空经济政策密集发布",
    signalSources: ["财经新闻 RSS", "地方政策摘要", "行业媒体源"],
    whatHappened: "多个地区继续发布低空经济支持政策，低空基础设施和应用试点进入落地观察阶段。",
    whyItMatters: "政策可能改变资金流向和行业预期，但兑现周期较长，需要分清基础设施、运营和设备制造的受益顺序。",
    transmissionChain: ["政策方向明确", "试点和预算增加", "基础设施与空管系统先受益", "应用场景逐步验证", "订单和收入兑现"],
    beneficiaryIndustries: ["无人机", "空管系统", "低空基础设施", "通航运营"],
    beneficiaryCompanyTypes: ["有真实订单的设备商", "低空空管和基础设施供应商", "具备合规运营能力的平台公司"],
    relatedTickers: [
      {name: "中无人机", code: "688297", market: "A_SHARE", reason: "无人机产业链标的，可用于研究政策兑现路径。"},
      {name: "航天电子", code: "600879", market: "A_SHARE", reason: "航电和无人系统相关业务可作为产业链样本。"},
      {name: "亿航智能", code: "EH", market: "US", reason: "低空载人航空器商业化观察对象。"},
    ],
    riskPoints: ["政策热度不等于订单兑现。", "商业模式可能尚未跑通。", "主题交易过热后回撤可能较大。"],
    nextQuestions: ["哪些环节先拿到预算和订单？", "收入确认周期有多长？", "行业估值是否已经透支政策预期？"],
    scoreBreakdown: {signalStrength: 14, chainClarity: 15, fundamentalRelevance: 13, valuationSafety: 12, userFit: 13},
    opportunityScore: 67,
    suitabilityScore: 62,
    riskLevel: "medium",
    status: "new",
    conclusion: "仅作为趋势记录，等待政策转化为订单和财务数据后再提高优先级。",
    createdAt: now,
  },
  {
    id: "analysis-consumer-contrarian",
    signalId: "signal-consumer-contrarian",
    title: "消费龙头估值压缩后的反向观察",
    signalSources: ["财经新闻 RSS", "估值摘要", "持仓观察"],
    whatHappened: "消费板块情绪偏弱，部分优质公司估值回落，但基本面暂未出现同等幅度恶化。",
    whyItMatters: "反向机会的关键不是下跌本身，而是基本面稳定、估值回到合理区间，并出现修复催化。",
    transmissionChain: ["市场情绪低迷", "估值压缩", "检查基本面是否恶化", "寻找现金流和品牌壁垒仍稳定的公司", "等待业绩或估值修复催化"],
    beneficiaryIndustries: ["食品饮料", "品牌消费", "互联网平台"],
    beneficiaryCompanyTypes: ["现金流稳定的品牌公司", "估值进入合理区间的平台公司", "有分红或回购支撑的龙头"],
    relatedTickers: [
      {name: "贵州茅台", code: "600519", market: "A_SHARE", reason: "品牌壁垒和现金流较强，但需等待安全边际。"},
      {name: "腾讯控股", code: "00700", market: "HK", reason: "现金流较稳，估值和监管预期需要继续跟踪。"},
    ],
    riskPoints: ["消费复苏可能弱于预期。", "估值便宜不代表短期会修复。", "如果基本面开始恶化，反向机会会变成价值陷阱。"],
    nextQuestions: ["收入和利润是否仍稳定？", "估值是否进入自己的安全边际？", "是否存在明确回购、分红或业绩修复催化？"],
    scoreBreakdown: {signalStrength: 11, chainClarity: 13, fundamentalRelevance: 16, valuationSafety: 16, userFit: 15},
    opportunityScore: 71,
    suitabilityScore: 76,
    riskLevel: "medium",
    status: "new",
    conclusion: "加入观察池，重点验证基本面是否稳定和估值是否足够有安全边际。",
    createdAt: now,
  },
];

export const mockOpportunityDailyReports: OpportunityDailyReport[] = [
  {
    id: "report-2026-07-01",
    reportDate: now,
    summary: "今日机会雷达识别到 4 条研究线索：存储设备涨价分数最高，但风险也最高；机器人和低空经济处在高热度验证期；消费龙头属于反向观察，不适合用情绪直接交易。",
    topOpportunityIds: ["analysis-storage-price", "analysis-robot-demand", "analysis-consumer-contrarian"],
    ignoredNoise: ["单日社交媒体热搜但缺少产业链验证的短期话题", "只有股价波动、没有基本面信息的异动"],
    riskWarnings: ["新闻热度不等于投资价值。", "所有机会默认进入观察池，买入前仍需完成买入决策单。", "高分机会也必须验证估值和财务兑现。"],
    createdAt: now,
  },
];

export const mockOpportunityFeedback: OpportunityFeedback[] = [];

export const mockDecisions: TradeDecision[] = [
  {
    id: "decision-1",
    instrumentType: "fund",
    instrumentName: "沪深300指数增强",
    instrumentCode: "000300",
    action: "add",
    amount: 6000,
    reason: "宽基指数用于建立基础权益仓位，目前仓位较低，计划分三个月小额追加并观察回撤。",
    expectedHoldingPeriod: "long",
    maxAcceptableLossRate: 15,
    targetProfitRate: 15,
    stopLossCondition: "如果亏损超过 18% 且指数估值与基本面继续恶化，暂停追加。",
    takeProfitCondition: "达到 15% 收益后重新评估是否继续持有。",
    isEmotionDriven: false,
    confidenceLevel: 4,
    createdAt: now,
  },
];

export const mockReviews: ReviewRecord[] = [
  {
    id: "review-1",
    decisionId: "decision-1",
    instrumentType: "fund",
    instrumentName: "沪深300指数增强",
    action: "add",
    decisionDate: "2026-07-01",
    reviewDate: "2026-07-15",
    originalReason: "建立基础权益仓位，避免一次性买入。",
    actualResult: "价格仍有波动，但小额分批降低了心理压力。",
    profitRate: -1.8,
    disciplineFollowed: true,
    emotionalTrade: false,
    lesson: "分批计划比临时买入更容易执行。",
    nextImprovement: "下次买入前补充更明确的估值区间。",
    createdAt: now,
  },
];

export const initialState = {
  assets: mockAssets,
  funds: mockFunds,
  stocks: mockStocks,
  watchItems: mockWatchItems,
  decisions: mockDecisions,
  reviews: mockReviews,
  profile: defaultInvestorProfile,
  marketEvents: [storagePriceEvent],
  opportunitySources: mockOpportunitySources,
  rawExternalItems: mockRawExternalItems,
  opportunitySignals: mockOpportunitySignals,
  opportunityAnalyses: mockOpportunityAnalyses,
  opportunityDailyReports: mockOpportunityDailyReports,
  opportunityFeedback: mockOpportunityFeedback,
};
